# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='stxclock_api.Exchange')),
            ],
            options={
                'ordering': ('exchange', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Saturday', max_length=10)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend', to='stxclock_api.Exchange')),
            ],
            options={
                'ordering': ('exchange', 'day'),
            },
        ),
    ]
